### PR TITLE
New Feature : Import IoCs from an added MISP instance.

### PR DESCRIPTION
**Pull request by JulAkx**
This pull request grants the possibility to the user to import IoCs - that belong to the "Network Activity" category - from an added MISP (Malware Information Sharing Platform) instance.
If you don't know what MISP is please visit the following link https://www.misp-project.org/

### CODE REVIEW

**Comment by felixaime** [comment]
Hi JulAkx! Thanks for the PR, I'm gonna to test it / review it and push it these next days. Sorry for the late reply...
Have a good day,
Félix.

**Comment by felixaime** [comment]
Hello !

I'm back on your PR after some vacation. Thanks for your work, I really appreciate. First, your code looks good and can be implemented. There is one mistake, you haven't added the blueprint to the URL so I had some errors the first time when I tried to use it.

What I think to do regarding to PR is to push it on a new branch to work on it (mostly on UI design). Moreover, can be good to add the MISP import in the watchers to import IOCs automatically in TC when it starts, what you think on that ?

Félix.

**Comment by JulAkx** [comment]
Hello !
Thanks for your feedback !
I'm sorry that you had some errors. I thought I had tested it right. I hope it didn't take you too long to figure out what it was.

Your suggestion is good, adding the misp import IOCs to the watchers could be really appreciated. I don't how much work it represent though
For the UI / design part I tried my best to stick to main theme so feel free to reorganize it the way you think it fits the best to the app

**Comment by felixaime** [comment]
Ok cool ! I'm gonna to work on it next week! (and maybe implement OpenCTI API too)
Thanks a lot,

Félix.

**Comment by felixaime** [comment]
Hello !

I've improved your PR by (still not committed in the misp branch) :

- Testing the connection to the MISP instance before adding it ;
- Listing the instances with the status (connected / not connected) ;
- Adding watchers support (once TC is started, the IOCs are grabbed from the MISP instances) ;
- Grab the IOCs via watchers from the last synchronization date
- Changing the design (and removing the edition, sorry) ;
- Some code optimization.

**Pull request merged**
